version: "3.9"

services:
  nextcloud:
    image: kefaslungu/hng-nextcloud
    container_name: hng-nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
      - HNG-nginx-logs:/var/log/nginx:ro
    networks:
      - hng-network

  nginx:
    image: nginx:alpine
    container_name: hng-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HNG-nginx-logs:/var/log/nginx
    networks:
      - hng-network
    depends_on:
      - nextcloud

  detector:
    build: ./detector
    container_name: hng-detector
    restart: unless-stopped

    # REQUIRED for iptables to work
    network_mode: host

    # REQUIRED for iptables permissions
    cap_add:
      - NET_ADMIN

    volumes:
      - HNG-nginx-logs:/var/log/nginx:ro
      - ./detector/config.yaml:/app/config.yaml

    environment:
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}

    depends_on:
      - nginx

volumes:
  HNG-nginx-logs:
  nextcloud_data:

networks:
  hng-network:
    driver: bridge
    