services:

  nginx:
    image: nginx:latest
    container_name: hng-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HNG-nginx-logs:/var/log/nginx
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: hng-nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - HNG-nginx-logs:/var/log/nginx:ro
    restart: unless-stopped

volumes:
  HNG-nginx-logs:
  nextcloud_data:
