events {}

http {

log_format json_logs escape=json
'{'
'"source_ip":"$remote_addr",'
'"timestamp":"$time_iso8601",'
'"method":"$request_method",'
'"path":"$request_uri",'
'"status":"$status",'
'"response_size":"$body_bytes_sent"'
'}';

access_log /var/log/nginx/hng-access.log json_logs;

# MAIN APP
server {
    listen 80;
    server_name ntscomputers.dpdns.org;

    location / {
        proxy_pass http://hng-nextcloud:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# METRICS DASHBOARD
server {
    listen 80;
    server_name metrics.ntscomputers.dpdns.org;

    location / {
        proxy_pass http://172.17.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

}
