FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    sudo \
    procps \
    iproute2 \
    iptables \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x main.py

CMD ["python", "main.py"]